version: '2'
services:
  starter-bundle-test:
    build:
      context: ..
      dockerfile: .buildkite/Dockerfile
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_URL
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_COMMIT
      - BUILDKITE_JOB_ID
    working_dir: /home/starter-bundle-test
    volumes:
      - ..:/home/starter-bundle-test
